source 'https://rubygems.org'

gem 'rails', '3.2.11'
gem 'jquery-rails'
gem 'devise'
gem 'sanitize'
gem 'bootstrap-wysihtml5-rails'
gem 'foreigner'
gem 'immigrant'
gem 'will_paginate'
gem 'will_paginate-bootstrap'

group :development do
  gem 'debugger'
  gem 'sqlite3'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'bootstrap-sass'
  gem 'uglifier', '>= 1.0.3'
end


# Deploy with Capistrano
# gem 'capistrano'
#
# To use debugger
# gem 'omniauth'

# gem 'omniauth-facebook'
