source 'https://rubygems.org'

# Core stuff
gem 'rails', '3.2.11'
gem 'jquery-rails'

# Auth
gem 'devise'

# Clean html input
gem 'sanitize'

# wysiwyg
gem 'bootstrap-wysihtml5-rails'

# Foreign keys in db
gem 'foreigner'
gem 'immigrant'

# Pagination
gem 'will_paginate'
gem 'will_paginate-bootstrap'

# Save old versions of records in db
gem 'paper_trail', '~> 2'

# Serve static pages
gem 'high_voltage'

group :development do
  gem 'debugger'
  gem 'sqlite3'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'bootstrap-sass'
  gem 'uglifier', '>= 1.0.3'
end


# gem 'capistrano'
# gem 'omniauth'
# gem 'omniauth-facebook'
